---
- hosts: all
  roles:
    - role: hostname
    - role: hosts
    - role: base_packages
  tasks:
    - name: Create the masters groups
      add_host:
        name: '{{ item }}'
        groups: masters
      loop: "{{ groups['init_master'] + groups['more_master'] | default([]) }}"

- hosts:
    - masters
    - worker
  roles:
    - role: docker
    - role: kubelet

- hosts:
    - haproxy
  roles:
    - role: haproxy

- hosts: init_master
  roles:
    - role: kubeadm_bootstrap

- hosts: worker
  roles:
    - role: kubeadm_join_worker

- hosts: more_master
  roles:
    - role: kubeadm_join_master
