---
- hosts: master:worker
  tasks:
    - package:
        state: present
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
      tags:
        - basic

    - apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
      register: docker_deb

    - package:
        update_cache: true
      when: docker_deb is changed

    - package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
